mongodb:
  max:
    pool:
      size: 300
server:
  port : 8080


file:
  upload-dir: /home/goreit

spring:
  servlet:
    multipart:
     enabled: true
     max-file-size: 3MB
  application:
    name: opf2
  data:
    mongodb:
      database:  opf2
      authentication-database: admin
      host: localhost
      port: 27017
      password: admin
      username: admin

logging:
  level:
    org:
    springframework: ERROR