mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
    name: opf2
  data:
    mongodb:
      database:  opf2
      authentication-database: admin
      host: localhost
      port: 27017
      password: admin
      username: admin